import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

type Reason = "homophone" | "same-char-homophone";

interface RimeEntry {
  word: string;
  pinyin: string;
  normalizedPinyin: string;
  weight: number;
}

interface Replacement {
  text: string;
  reason: Reason;
  score: number;
}

interface SourceDictionary {
  path: string;
  label: string;
}

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..");
const sourceDictionaries: readonly SourceDictionary[] = [
  {
    path: resolve(repoRoot, "third_party/rime-luna-pinyin/luna_pinyin.dict.yaml"),
    label: "rime/rime-luna-pinyin luna_pinyin.dict.yaml",
  },
  {
    path: resolve(repoRoot, "third_party/rime-pinyin-simp/pinyin_simp.dict.yaml"),
    label: "rime/rime-pinyin-simp pinyin_simp.dict.yaml",
  },
];
const outputPath = resolve(repoRoot, "src/data/zh-ime-confusions.generated.ts");
const MIN_SCORE = 0.55;
const MAX_SOURCE_LENGTH = 5;
const TOP_K = 5;

const entries = sourceDictionaries.flatMap((source) =>
  parseRimeDictionary(readFileSync(source.path, "utf8")),
);
const wordEntries = entries.filter((entry) => {
  const length = Array.from(entry.word).length;
  return length >= 2 && length <= MAX_SOURCE_LENGTH;
});
const grouped = groupBy(wordEntries, (entry) => entry.normalizedPinyin);
const confusions = buildConfusionMap(grouped);

writeFileSync(outputPath, renderConfusionMap(confusions), "utf8");

console.log(
  `Generated ${Object.keys(confusions).length} Chinese IME confusion entries from ${entries.length} dictionary entries across ${sourceDictionaries.length} sources.`,
);

function parseRimeDictionary(input: string): RimeEntry[] {
  const lines = input.split(/\r?\n/u);
  const bodyStart = lines.findIndex((line) => line.trim() === "...");

  if (bodyStart === -1) {
    throw new Error("Rime dictionary header terminator `...` not found");
  }

  const entries: RimeEntry[] = [];

  for (const line of lines.slice(bodyStart + 1)) {
    const trimmed = line.trimEnd();

    if (trimmed === "" || trimmed.startsWith("#")) {
      continue;
    }

    const [word, pinyin, weightText] = trimmed.split("\t");

    if (!word || !pinyin || !isAllHan(word)) {
      continue;
    }

    const normalizedPinyin = normalizePinyin(pinyin);

    if (normalizedPinyin === "") {
      continue;
    }

    const parsedWeight = Number(weightText);

    entries.push({
      word,
      pinyin,
      normalizedPinyin,
      weight: Number.isFinite(parsedWeight) && parsedWeight > 0 ? parsedWeight : 1,
    });
  }

  return entries;
}

function buildConfusionMap(
  grouped: ReadonlyMap<string, readonly RimeEntry[]>,
): Record<string, Replacement[]> {
  const result: Record<string, Replacement[]> = {};

  for (const group of grouped.values()) {
    const maxWeight = Math.max(...group.map((entry) => entry.weight));

    for (const source of group) {
      const replacements = group
        .filter((candidate) => candidate.word !== source.word)
        .filter(
          (candidate) =>
            Math.abs(
              Array.from(candidate.word).length - Array.from(source.word).length,
            ) <= 1,
        )
        .map((candidate) => ({
          text: candidate.word,
          reason: getReason(source.word, candidate.word),
          score: scoreCandidate(source.word, candidate, maxWeight),
        }))
        .filter((candidate) => candidate.score >= MIN_SCORE)
        .sort(compareReplacements)
        .slice(0, TOP_K);

      if (replacements.length > 0) {
        result[source.word] = replacements;
      }
    }
  }

  return result;
}

function scoreCandidate(
  source: string,
  candidate: RimeEntry,
  maxWeight: number,
): number {
  const frequencyScore = Math.log1p(candidate.weight) / Math.log1p(maxWeight);
  const sharedCharScore =
    sharedCharCount(source, candidate.word) /
    Math.max(Array.from(source).length, Array.from(candidate.word).length);
  const lengthSimilarityScore =
    1 -
    Math.abs(Array.from(source).length - Array.from(candidate.word).length) /
      Math.max(Array.from(source).length, Array.from(candidate.word).length);

  return roundScore(
    frequencyScore * 0.6 + sharedCharScore * 0.25 + lengthSimilarityScore * 0.15,
  );
}

function renderConfusionMap(confusions: Record<string, Replacement[]>): string {
  const maxLength = Math.max(
    0,
    ...Object.keys(confusions).map((word) => Array.from(word).length),
  );
  const sourceLabels = sourceDictionaries
    .map((source) => `// Source: ${source.label}`)
    .join("\n");

  return `// Generated by tools/build-zh-ime-confusions.ts.
${sourceLabels}
// Licenses: LGPL-3.0 and Apache-2.0
// Do not edit manually.

export interface ZhImeReplacement {
  text: string;
  reason: "homophone" | "near-homophone" | "same-char-homophone" | "shape";
  score: number;
}

export const ZH_IME_CONFUSIONS: Readonly<
  Record<string, readonly ZhImeReplacement[]>
> = ${JSON.stringify(confusions)} as const;

export const MAX_ZH_IME_SOURCE_LENGTH = ${maxLength};
`;
}

function normalizePinyin(value: string): string {
  return value
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .toLowerCase()
    .replace(/ü/gu, "v")
    .replace(/u:/gu, "v")
    .replace(/[1-5]/gu, "")
    .replace(/\s+/gu, "");
}

function groupBy<T>(
  values: readonly T[],
  keyOf: (value: T) => string,
): Map<string, T[]> {
  const groups = new Map<string, T[]>();

  for (const value of values) {
    const key = keyOf(value);
    const group = groups.get(key);

    if (group) {
      group.push(value);
    } else {
      groups.set(key, [value]);
    }
  }

  return groups;
}

function sharedCharCount(left: string, right: string): number {
  const rightChars = new Set(Array.from(right));
  return Array.from(new Set(Array.from(left))).filter((char) => rightChars.has(char))
    .length;
}

function getReason(source: string, candidate: string): Reason {
  return sharedCharCount(source, candidate) > 0
    ? "same-char-homophone"
    : "homophone";
}

function compareReplacements(left: Replacement, right: Replacement): number {
  if (left.score !== right.score) {
    return right.score - left.score;
  }

  return left.text.localeCompare(right.text, "zh-Hans-CN");
}

function isAllHan(value: string): boolean {
  return Array.from(value).every((char) => /^\p{Script=Han}$/u.test(char));
}

function roundScore(value: number): number {
  return Math.round(value * 1000) / 1000;
}
